/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.digitalbias.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int preferences_icon=0x7f020001;
    }
    public static final class id {
        public static final int back_book=0x7f060004;
        public static final int back_home=0x7f060000;
        public static final int back_volume=0x7f060001;
        public static final int book_subtitle=0x7f060003;
        public static final int book_title=0x7f060002;
        public static final int cancelButton=0x7f06000d;
        public static final int chapter_title=0x7f060005;
        public static final int databaseEntry=0x7f060009;
        public static final int databaseText=0x7f060008;
        public static final int okButton=0x7f06000c;
        public static final int open_preferences=0x7f06000f;
        public static final int text1=0x7f060007;
        public static final int themeEntry=0x7f06000b;
        public static final int themeText=0x7f06000a;
        public static final int verses=0x7f060006;
        public static final int volume_title=0x7f06000e;
    }
    public static final class layout {
        public static final int book_list=0x7f030000;
        public static final int chapter=0x7f030001;
        public static final int directory_list=0x7f030002;
        public static final int file_row=0x7f030003;
        public static final int main=0x7f030004;
        public static final int preferences=0x7f030005;
        public static final int scripture_list=0x7f030006;
        public static final int scripture_row=0x7f030007;
        public static final int volume_list=0x7f030008;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int no_files=0x7f040003;
        public static final int no_volumes=0x7f040002;
        public static final int preferences_title=0x7f040005;
        public static final int to_top=0x7f040004;
    }
}
