/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.digitalbias.android;

public final class R {
    public static final class array {
        public static final int font_size=0x7f040001;
        /**  Used in View/Spinner1.java 
         */
        public static final int themes=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int download=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int next=0x7f020002;
        public static final int preferences_icon=0x7f020003;
        public static final int prev=0x7f020004;
    }
    public static final class id {
        public static final int back_book=0x7f070004;
        public static final int back_home=0x7f070000;
        public static final int back_volume=0x7f070001;
        public static final int book_subtitle=0x7f070003;
        public static final int book_title=0x7f070002;
        public static final int cancelButton=0x7f070014;
        public static final int chapter_title=0x7f070005;
        public static final int chooseFileButton=0x7f07000e;
        public static final int databaseEntry=0x7f07000d;
        public static final int databaseText=0x7f07000c;
        public static final int done_button=0x7f070007;
        public static final int download_database=0x7f070018;
        public static final int fontSizeSpinner=0x7f070012;
        public static final int fontSizeText=0x7f070011;
        public static final int okButton=0x7f070013;
        public static final int open_next=0x7f07001a;
        public static final int open_preferences=0x7f070017;
        public static final int open_previous=0x7f070019;
        public static final int progress=0x7f070009;
        public static final int refresh_button=0x7f070008;
        public static final int scripture_layout=0x7f070015;
        public static final int text1=0x7f07000b;
        public static final int themeSpinner=0x7f070010;
        public static final int themeText=0x7f07000f;
        public static final int title=0x7f070016;
        public static final int verses=0x7f070006;
        public static final int volume_title=0x7f07000a;
    }
    public static final class layout {
        public static final int book_list=0x7f030000;
        public static final int chapter=0x7f030001;
        public static final int database_dialog=0x7f030002;
        public static final int directory_list=0x7f030003;
        public static final int file_row=0x7f030004;
        public static final int main=0x7f030005;
        public static final int preferences=0x7f030006;
        public static final int scripture_list=0x7f030007;
        public static final int scripture_row=0x7f030008;
        public static final int volume_list=0x7f030009;
    }
    public static final class menu {
        public static final int browse_menu=0x7f060000;
        public static final int chapter_menu=0x7f060001;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int bad_database=0x7f050000;
        public static final int download_activity_cancel=0x7f05000b;
        public static final int download_activity_download_stopped=0x7f050014;
        public static final int download_activity_progress=0x7f05000c;
        public static final int download_activity_quit=0x7f050016;
        public static final int download_activity_retry=0x7f050015;
        public static final int download_activity_time_remaining=0x7f05000e;
        public static final int download_activity_time_remaining_days=0x7f050013;
        public static final int download_activity_time_remaining_hours=0x7f050012;
        public static final int download_activity_time_remaining_minutes=0x7f050010;
        public static final int download_activity_time_remaining_seconds=0x7f050011;
        public static final int download_activity_time_remaining_unknown=0x7f05000f;
        public static final int download_activity_title=0x7f05000a;
        public static final int download_activity_verifying=0x7f05000d;
        public static final int download_title=0x7f050007;
        public static final int next_title=0x7f050009;
        public static final int no_downloads=0x7f050003;
        public static final int no_files=0x7f050004;
        public static final int no_volumes=0x7f050002;
        public static final int preferences_title=0x7f050006;
        public static final int previous_title=0x7f050008;
        public static final int to_top=0x7f050005;
    }
}
